platyst ass2w.pls > ass2w.out
platyst ass2r.pls > ass2r.out
platyst a2empty.pls > a2empty.out
platyst a2error.pls > a2error.out
platyst a2comm.pls > a2comm.out
platyst a2stre.pls > a2stre.out
platyst a2str.pls > a2str.out
platyst a2slash.pls > a2slash.out
platyst a2single.pls > a2single.out
platyst a2quot.pls > a2quot.out
platyst a2op.pls > a2op.out
platyst a2op2.pls > a2op2.out
platyst a2op3.pls > a2op3.out
platyst a2elbow.pls > a2elbow.out
platyst a2java.pls > a2java.out
platyst a2strcmt.pls >a2strcmt.out
platyst a2hex.pls > a2hex.out
platyst a2comm2.pls > a2comm2.out
platyst a2comm3.pls > a2comm3.out