platy a2empty.pls > a2empty.out
platy a2error.pls > a2error.out
platy a2hello.pls > a2hello.out
platy a4AND.pls > a4AND.out
platy a4EOF.pls > a4EOF.out
platy a4for.pls > a4for.out
platy a4if.pls > a4if.out
platy a4math.pls > a4math.out
platy a4math2.pls > a4math2.out
platy a4nest.pls > a4nest.out
platy a4num.pls > a4num.out
platy a4num2.pls > a4num2.out
platy a4prg.pls > a4prg.out
platy a4read.pls > a4read.out
platy a4state.pls > a4state.out
platy a4state2.pls > a4state2.out
platy a4stateE.pls > a4stateE.out
platy a4unary.pls > a4unary.out
platy a4unary2.pls > a4unary2.out
platy a4write.pls > a4write.out
platy ass1.pls > ass1.out
platy ass2r.pls > ass2r.out
platy ass2w.pls > ass2w.out
platy ass3m.pls > ass3m.out
platy ass3r.pls > ass3r.out
Test
