--SELECT * FROM TH188_HRSR_LETTER_SECTION;

INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Header','FR: Header',1);
  
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Subject','FR: Subject',2);
    
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Applicant Address','FR: Applicant Address',3);  
  
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Greeting','FR: Greeting',4);  
    
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Body Paragraph','FR: Body Paragraph',5);  
  
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Close','FR: Close',6);   
  
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Signature Line','FR: Signature Line',7);    
  
INSERT INTO TH188_HRSR_LETTER_SECTION (hrsr_letter_section_enm,hrsr_letter_section_fnm, display_order_num)
  VALUES ('Attachment','FR: Attachment',8);   
