--SELECT * FROM TH197_TI_PROFILE;


INSERT INTO TH197_TI_PROFILE (ti_profile_cd,ti_profile_enm, ti_profile_fnm, ti_bud_code_txt)
  VALUES ('1', 'TI General', 'TI Général', '41300');
  
INSERT INTO TH197_TI_PROFILE (ti_profile_cd,ti_profile_enm, ti_profile_fnm, ti_bud_code_txt)
  VALUES ('2', 'TI Aviation', 'TI Aviation', '41301');
  
INSERT INTO TH197_TI_PROFILE (ti_profile_cd,ti_profile_enm, ti_profile_fnm, ti_bud_code_txt)
  VALUES ('3', 'TI Marine', 'TI Marine', '41302');  
  
INSERT INTO TH197_TI_PROFILE (ti_profile_cd,ti_profile_enm, ti_profile_fnm, ti_bud_code_txt)
  VALUES ('4', 'TI Railway Safety', 'TI Sécurité ferroviaire', '41303');    
  
